apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-route
  namespace: portfolio
spec:
  parentRefs:
    - name: my-gateway
      namespace: nginx-gateway
  hostnames:
    - "portfolio.jboureux.fr"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: portfolio
          port: 80
